version: '3.8'

services:
  api-jwt:
    image: qi-agent-ss-jwt:latest
    container_name: qi-agent-ss-jwt
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Makassar
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
