version: '3.8'

services:
  api-jwt:
    image: qi-agent-ss-jwt:latest
    container_name: qi-agent-ss-jwt
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@172.18.0.7:5432/db_qi_agent
      - TZ=Asia/Makassar
      - JWT_SECRET_KEY=qi-agent-jwt-secret-key-2026
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=480
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - CORS_ORIGINS=["*"]
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
