"""initial_schema

Revision ID: c65b3ffbbdbf
Revises: 
Create Date: 2026-06-07 15:15:23.555638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c65b3ffbbdbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esic_tm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nrp', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.Text(), nullable=True),
    sa.Column('dept', sa.String(length=20), nullable=True),
    sa.Column('divisi', sa.String(length=20), nullable=True),
    sa.Column('distrik', sa.String(length=10), nullable=True),
    sa.Column('posisi', sa.Text(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('dokumen_diakses', sa.Text(), nullable=True),
    sa.Column('dokumen_mtd', sa.Text(), nullable=True),
    sa.Column('monthly_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tb_esic'
    )
    op.create_index(op.f('ix_tb_esic_esic_tm_id'), 'esic_tm', ['id'], unique=False, schema='tb_esic')
    op.create_index(op.f('ix_tb_esic_esic_tm_nrp'), 'esic_tm', ['nrp'], unique=False, schema='tb_esic')
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('new_records', sa.Integer(), nullable=True),
    sa.Column('updated_records', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tb_ss'
    )
    op.create_index(op.f('ix_tb_ss_import_log_id'), 'import_log', ['id'], unique=False, schema='tb_ss')
    op.create_table('manpower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nrp', sa.String(length=12), nullable=True),
    sa.Column('nama', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('crew', sa.Text(), nullable=True),
    sa.Column('posisi', sa.Text(), nullable=True),
    sa.Column('target_ss', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('jabatan', sa.Text(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tb_ss'
    )
    op.create_index(op.f('ix_tb_ss_manpower_id'), 'manpower', ['id'], unique=False, schema='tb_ss')
    op.create_index(op.f('ix_tb_ss_manpower_nrp'), 'manpower', ['nrp'], unique=False, schema='tb_ss')
    op.create_table('pin_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tb_ss'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nrp', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='tb_ss'
    )
    op.create_index(op.f('ix_tb_ss_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='tb_ss')
    op.create_index(op.f('ix_tb_ss_refresh_tokens_nrp'), 'refresh_tokens', ['nrp'], unique=False, schema='tb_ss')
    op.create_table('ss_records',
    sa.Column('no_ss', sa.String(length=30), nullable=False),
    sa.Column('judul', sa.Text(), nullable=False),
    sa.Column('nrp', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.Text(), nullable=True),
    sa.Column('dept', sa.String(length=20), nullable=True),
    sa.Column('divisi', sa.String(length=20), nullable=True),
    sa.Column('distrik', sa.String(length=10), nullable=True),
    sa.Column('tanggal_laporan', sa.Date(), nullable=True),
    sa.Column('grade_ss', sa.String(length=5), nullable=True),
    sa.Column('kualitas_ss', sa.String(length=50), nullable=True),
    sa.Column('kategori_ss', sa.String(length=50), nullable=True),
    sa.Column('reward_ss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status_karyawan', sa.String(length=10), nullable=True),
    sa.Column('manfaat_financial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tanggal_menilai', sa.Date(), nullable=True),
    sa.Column('dinilai_oleh', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('latest_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('no_ss'),
    schema='tb_ss'
    )
    op.create_index(op.f('ix_tb_ss_ss_records_current_status'), 'ss_records', ['current_status'], unique=False, schema='tb_ss')
    op.create_index(op.f('ix_tb_ss_ss_records_dept'), 'ss_records', ['dept'], unique=False, schema='tb_ss')
    op.create_index(op.f('ix_tb_ss_ss_records_nrp'), 'ss_records', ['nrp'], unique=False, schema='tb_ss')
    op.create_index(op.f('ix_tb_ss_ss_records_source'), 'ss_records', ['source'], unique=False, schema='tb_ss')
    op.create_table('users',
    sa.Column('nrp', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nrp'),
    schema='tb_ss'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_ss_records_source'), table_name='ss_records', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_ss_records_nrp'), table_name='ss_records', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_ss_records_dept'), table_name='ss_records', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_ss_records_current_status'), table_name='ss_records', schema='tb_ss')
    op.drop_table('ss_records', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_refresh_tokens_nrp'), table_name='refresh_tokens', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_refresh_tokens_id'), table_name='refresh_tokens', schema='tb_ss')
    op.drop_table('refresh_tokens', schema='tb_ss')
    op.drop_table('pin_state', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_manpower_nrp'), table_name='manpower', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_manpower_id'), table_name='manpower', schema='tb_ss')
    op.drop_table('manpower', schema='tb_ss')
    op.drop_index(op.f('ix_tb_ss_import_log_id'), table_name='import_log', schema='tb_ss')
    op.drop_table('import_log', schema='tb_ss')
    op.drop_index(op.f('ix_tb_esic_esic_tm_nrp'), table_name='esic_tm', schema='tb_esic')
    op.drop_index(op.f('ix_tb_esic_esic_tm_id'), table_name='esic_tm', schema='tb_esic')
    op.drop_table('esic_tm', schema='tb_esic')
    # ### end Alembic commands ###
